define

aspect-error sub rule,

when {
  (hasproperty: $a1, defines: $spo1, ispropertytype: $ptype1) isa property;
  $a1 has aspect_data_value $adv1;
  $a1 has internal_reference $intref1;
  $ptype1 has aspect_name $aname1;
  (representedby: $spo1, represents: $po1, hasrepresentingsystem: $sys1) isa representation;
  $po1 has ident $po_ident1;
  $spo1 has name $spo1name;
  $sys1 has sysname $sysname1;
  

  (hasproperty: $a2, defines: $spo2, ispropertytype: $ptype2) isa property;
  $a2 has aspect_data_value $adv2;
  $a2 has internal_reference $intref2;
  $ptype2 has aspect_name $aname2;
  (representedby: $spo2, represents: $po2, hasrepresentingsystem: $sys2) isa representation;
  $po2 has ident $po_ident2;
  $spo2 has name $spo2name;
  $sys2 has sysname $sysname2;
  
  $po_ident1 == $po_ident2;
  $aname1 == $aname2 ; 
  $adv1 != $adv2 ;
  $spo1name != $spo2name ;

}, then {

     (errorneousAspectValue: $a1, errorneousAspectValue: $a2) isa alertDirectRelationPair;

};
